Fix e2e for helm
Lodaing kind-e2e/lib_operator_deploy_subm.sh in e2e was causing an error [1].
Moved it to load only when running e2e with operator.
Also had to move the "vars" func outside the deploy file since we don't
load it for helm.
Also disabled the checks in helm since theyre broken, eg [2]

[1] ++ cp -a ../operators/go/submariner-operator/. /root/go/src/github.com/submariner-operator/submariner-operator/
cp: cannot stat '../operators/go/submariner-operator/.': No such file or directory
[submariner]$ ./scripts/e2e onetime 1.14.2 false false helm
FATA[0071] exit status 1
make: *** [Makefile:17: e2e] Error 1

[2] + verify_subm_engine_pod
+ kubectl wait --for=condition=Ready pods -l app=submariner-engine --timeout=120s --namespace=operators
error: no matching resources found

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>